export const STICKER_LIBRARY = [
  { name: "house vers. 1", url: "/stickers/house.png" },
  { name: "house vers. 2", url: "/stickers/stardewvalleyhouse.png" },
  { name: "townhouse vers. 1", url: "/stickers/townhouseclipart.png" },
  { name: "townhouse vers. 2", url: "/stickers/townhomeclipart2.png" },
  { name: "townhouse vers. 3", url: "/stickers/townhouseclipart3.png" },
  { name: "apartment building", url: "/stickers/building.png" },
  { name: "tree", url: "/stickers/trees.png" },
  { name: "palm tree from animal crossing", url: "/stickers/animalcrossingpalmtree.png" },
  { name: "peach tree from animal crossing", url: "/stickers/animalcrossingtree.png" },
  { name: "tree from terraria", url: "/stickers/terrariatree.png" },
  { name: "grass strip vers. 1", url: "/stickers/grassstrip.png" },
  { name: "grass strip vers. 2", url: "/stickers/grassstrip2.png" },
  { name: "castle", url: "/stickers/castle.png" },
  { name: "bridge", url: "/stickers/bridge.png" },
  { name: "bubbles", url: "/stickers/bubbles.png" },
  { name: "sun", url: "/stickers/sun.png" },
  { name: "crescent moon", url: "/stickers/crescentmoon.png" },
  { name: "hot spring", url: "/stickers/hotspring.png" },
  { name: "bunny", url: "/stickers/bunny.png" },
  { name: "cats", url: "/stickers/cats.png" },
  { name: "KFC fried chicken", url: "/stickers/chicken.png" },
  { name: "road", url: "/stickers/road.png" },
  { name: "daffodil", url: "/stickers/daffodils.png" },
  { name: "tulips", url: "/stickers/tulips.png" },
  { name: "rose", url: "/stickers/rose.png" },
  { name: "picture frame", url: "/stickers/pictureframe.png" },
  { name: "platform from terraria", url: "/stickers/terrariaplatform.png" },
  { name: "Campbells chicken noodle soup", url: "/stickers/campbells.png" },
  { name: "carousel", url: "/stickers/carousel.png" },
  { name: "Campbells chicken noodle soup", url: "/stickers/swingset.png" },

];
