export const STICKER_LIBRARY = [
  { name: "house vers. 1", url: "/stickers/house.png" },
  { name: "house vers. 2", url: "/stickers/stardewvalleryhouse.png" },
  { name: "townhouse vers. 1", url: "/stickers/townhouseclipart.png" },
  { name: "townhouse vers. 2", url: "/stickers/townhomeclipart2.png" },
  { name: "townhouse vers. 3", url: "/stickers/townhouseclipart3.png" },
  { name: "apartment building", url: "/stickers/apartmentbuilding.png" },
  { name: "tree", url: "/stickers/trees.png" },
  { name: "castle", url: "/stickers/castle.png" },
  { name: "bubbles", url: "/stickers/bubbles.png" },
  { name: "sun", url: "/stickers/sun.png" },
  { name: "hot spring", url: "/stickers/hotspring.png" },
  { name: "bunny", url: "/stickers/bunny.png" },
  { name: "cats", url: "/stickers/cats.png" },
  { name: "KFC fried chicken", url: "/stickers/chicken.png" },
  { name: "road", url: "/stickers/road.png" },
  { name: "daffodil", url: "/stickers/daffodils.png" },
  { name: "tulips", url: "/stickers/tulips.png" },
  { name: "picture frame", url: "/stickers/pictureframe.png" },

];
